"""Add sort id to sessions

Revision ID: 41c22efc36bc
Revises: 77a1655d2354
Create Date: 2021-11-09 17:31:28.966701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c22efc36bc'
down_revision = '77a1655d2354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('sort_id')

    # ### end Alembic commands ###
