"""Add known/ignore columns to algorithms

Revision ID: 4b75f48880a9
Revises: f10391638d8a
Create Date: 2021-12-05 02:21:18.727435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b75f48880a9'
down_revision = 'f10391638d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algorithms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('known', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ignore', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algorithms', schema=None) as batch_op:
        batch_op.drop_column('ignore')
        batch_op.drop_column('known')

    # ### end Alembic commands ###
