"""Add autocalibrate setting

Revision ID: 52906ed112d0
Revises: a7952048db87
Create Date: 2021-11-20 00:26:01.122549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52906ed112d0'
down_revision = 'a7952048db87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_calibrate', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('auto_calibrate')

    # ### end Alembic commands ###
