"""Add notify setting to session table

Revision ID: 65829dfd52e1
Revises: 721b75b20654
Create Date: 2021-12-05 19:39:36.731235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65829dfd52e1'
down_revision = '721b75b20654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_every_n_solves', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('notify_every_n_solves')

    # ### end Alembic commands ###
