"""Update algorithm tables to separate algs/cases

Revision ID: 7021e98eebf7
Revises: 722ad49cd0a5
Create Date: 2021-12-02 21:48:01.802726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7021e98eebf7'
down_revision = '722ad49cd0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alg_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('alg_set', sa.String(length=32), nullable=True),
    sa.Column('alg_nb', sa.String(length=32), nullable=True),
    sa.Column('diagram', sa.String(length=32), nullable=True),
    sa.Column('diag_type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alg_cases'))
    )
    with op.batch_alter_table('algorithms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alg_case_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_algorithms_alg_case_id_alg_cases'), 'alg_cases', ['alg_case_id'], ['id'])
        batch_op.drop_column('alg_set')
        batch_op.drop_column('alg_nb')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algorithms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alg_nb', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('alg_set', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_algorithms_alg_case_id_alg_cases'), type_='foreignkey')
        batch_op.drop_column('alg_case_id')

    op.drop_table('alg_cases')
    # ### end Alembic commands ###
