"""Add solve id for cached best stats

Revision ID: 721b75b20654
Revises: 4b75f48880a9
Create Date: 2021-12-05 19:21:17.248412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '721b75b20654'
down_revision = '4b75f48880a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cached_stats_best_solve_id', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('cached_stats_best_solve_id')

    # ### end Alembic commands ###
