"""Add solve_nb column to solves

Revision ID: 7f05b5f7d054
Revises: 8f98215eba8b
Create Date: 2022-01-05 16:00:45.714338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f05b5f7d054'
down_revision = '8f98215eba8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solve_nb', sa.Integer(), nullable=True))
        batch_op.create_index('solve_nb_idx', ['solve_nb'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solves', schema=None) as batch_op:
        batch_op.drop_index('solve_nb_idx')
        batch_op.drop_column('solve_nb')

    # ### end Alembic commands ###
