"""Change scramble_type to int, add puzzle_type in session

Revision ID: 8f98215eba8b
Revises: 1190e799b8e5
Create Date: 2021-12-30 16:19:06.712116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f98215eba8b'
down_revision = '1190e799b8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('scramble_type', new_column_name='puzzle_type')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scramble_type', sa.Integer, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('scramble_type')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('puzzle_type', new_column_name='scramble_type')

    # ### end Alembic commands ###
