"""Add raw smart data column

Revision ID: a7952048db87
Revises: 41c22efc36bc
Create Date: 2021-11-10 20:19:31.902542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7952048db87'
down_revision = '41c22efc36bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smart_data_raw', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solves', schema=None) as batch_op:
        batch_op.drop_column('smart_data_raw')

    # ### end Alembic commands ###
