"""Add alg groups and f2l slots

Revision ID: f10391638d8a
Revises: 7021e98eebf7
Create Date: 2021-12-03 03:01:41.706995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10391638d8a'
down_revision = '7021e98eebf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alg_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alg_group', sa.String(length=32), nullable=True))

    with op.batch_alter_table('algorithms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f2l_slot', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algorithms', schema=None) as batch_op:
        batch_op.drop_column('f2l_slot')

    with op.batch_alter_table('alg_cases', schema=None) as batch_op:
        batch_op.drop_column('alg_group')

    # ### end Alembic commands ###
